# SRAM FBM result viewer
# Python 3.7+
#
# Usage:
#   py SRAM_FBM_Viewer.py
#
# This tool reads result/failbit_labeled.csv generated by SRAM_FBM_Classifier.py.

import os
import threading
import tkinter as tk
from tkinter import filedialog, messagebox, ttk

import pandas as pd

import matplotlib

matplotlib.use("TkAgg")
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2Tk
from matplotlib.figure import Figure


DEFAULT_LABELED_CSV = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "result",
    "failbit_labeled.csv",
)

BASE_COLS = [
    "lot_id",
    "wafer_id",
    "test_time",
    "device#",
    "diex",
    "diey",
    "macro",
    "testname",
    "condition",
    "physical_x",
    "physical_y",
    "pattern_name",
    "pattern_id",
]

SCAN_COLS = [
    "lot_id",
    "wafer_id",
    "condition",
]

GROUP_COLS = [
    "lot_id",
    "wafer_id",
    "device#",
    "diex",
    "diey",
    "macro",
    "condition",
]

GROUP_KEY_COL = "_fbm_group_key"
GROUP_KEY_SEP = "\x1f"
PAGE_ROWS = 3
PAGE_COLS = 3
PAGE_SIZE = PAGE_ROWS * PAGE_COLS


def compact_value(value):
    if pd.isna(value):
        return "NA"

    text = str(value)
    if text.endswith(".0"):
        text = text[:-2]
    return text


def parse_range(min_text, max_text):
    min_text = min_text.strip()
    max_text = max_text.strip()
    if not min_text and not max_text:
        return None

    try:
        low = float(min_text) if min_text else None
        high = float(max_text) if max_text else None
    except ValueError:
        raise ValueError("range must be numeric")

    if low is not None and high is not None and low > high:
        low, high = high, low

    return low, high


class MultiSelectMenu(ttk.Menubutton):
    def __init__(self, master, label, command=None):
        self.text_var = tk.StringVar(value="%s: All" % label)
        super().__init__(master, textvariable=self.text_var)
        self.label = label
        self.command = command
        self.menu = tk.Menu(self, tearoff=False)
        self["menu"] = self.menu
        self.vars = {}
        self.options = []

    def set_options(self, options, selected=None):
        self.options = [str(v) for v in options]
        selected_set = set(str(v) for v in selected) if selected is not None else None
        self.vars = {}
        self.menu.delete(0, tk.END)
        self.menu.add_command(label="Select all", command=self.select_all)
        self.menu.add_command(label="Clear", command=self.clear)
        self.menu.add_separator()

        for option in self.options:
            var = tk.BooleanVar(value=True if selected_set is None else option in selected_set)
            self.vars[option] = var
            self.menu.add_checkbutton(label=option, variable=var, command=self._changed)

        self._refresh_label()

    def selected_values(self):
        return [option for option, var in self.vars.items() if var.get()]

    def is_all_selected(self):
        return len(self.selected_values()) == len(self.options)

    def select_all(self):
        for var in self.vars.values():
            var.set(True)
        self._changed()

    def clear(self):
        for var in self.vars.values():
            var.set(False)
        self._changed()

    def _changed(self):
        self._refresh_label()
        if self.command:
            self.command()

    def _refresh_label(self):
        selected_count = len(self.selected_values())
        total_count = len(self.options)
        if total_count == 0 or selected_count == total_count:
            text = "%s: All" % self.label
        elif selected_count == 0:
            text = "%s: None" % self.label
        else:
            text = "%s: %d/%d" % (self.label, selected_count, total_count)
        self.text_var.set(text)


class MultiSelectList(ttk.Frame):
    def __init__(self, master, label, command=None, height=5, width=18):
        super().__init__(master)
        self.label = label
        self.command = command
        self.options = []
        self.text_var = tk.StringVar(value="%s: All" % label)
        self._updating = False

        header = ttk.Frame(self)
        header.pack(fill=tk.X)
        ttk.Label(header, text=label).pack(side=tk.LEFT)
        ttk.Button(header, text="All", width=4, command=self.select_all).pack(side=tk.RIGHT)
        ttk.Button(header, text="Clear", width=5, command=self.clear).pack(side=tk.RIGHT, padx=(0, 3))

        body = ttk.Frame(self)
        body.pack(fill=tk.BOTH, expand=True)
        self.listbox = tk.Listbox(
            body,
            selectmode=tk.EXTENDED,
            exportselection=False,
            height=height,
            width=width,
        )
        scrollbar = ttk.Scrollbar(body, orient=tk.VERTICAL, command=self.listbox.yview)
        self.listbox.configure(yscrollcommand=scrollbar.set)
        self.listbox.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
        self.listbox.bind("<<ListboxSelect>>", self._on_select)

    def set_options(self, options, selected=None):
        self._updating = True
        self.options = [str(v) for v in options]
        selected_set = set(str(v) for v in selected) if selected is not None else None
        self.listbox.delete(0, tk.END)

        for option in self.options:
            self.listbox.insert(tk.END, option)

        if selected_set is None:
            self.listbox.selection_set(0, tk.END)
        else:
            for idx, option in enumerate(self.options):
                if option in selected_set:
                    self.listbox.selection_set(idx)

        self._updating = False
        self._refresh_label()

    def selected_values(self):
        return [self.options[idx] for idx in self.listbox.curselection()]

    def is_all_selected(self):
        return len(self.selected_values()) == len(self.options)

    def select_all(self):
        self._updating = True
        self.listbox.selection_set(0, tk.END)
        self._updating = False
        self._changed()

    def clear(self):
        self._updating = True
        self.listbox.selection_clear(0, tk.END)
        self._updating = False
        self._changed()

    def _on_select(self, _event):
        if not self._updating:
            self._changed()

    def _changed(self):
        self._refresh_label()
        if self.command:
            self.command()

    def _refresh_label(self):
        selected_count = len(self.selected_values())
        total_count = len(self.options)
        if total_count == 0 or selected_count == total_count:
            text = "%s: All" % self.label
        elif selected_count == 0:
            text = "%s: None" % self.label
        else:
            text = "%s: %d/%d" % (self.label, selected_count, total_count)
        self.text_var.set(text)


class FBMViewer(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("SRAM FBM Viewer")
        self.geometry("1280x1040")
        self.minsize(1180, 900)

        self.csv_path = tk.StringVar(value=DEFAULT_LABELED_CSV)
        self.status = tk.StringVar(value="Select failbit_labeled.csv, scan CSV, then load selected lot/wafer.")
        self.current_info = tk.StringVar(value="No macro loaded")
        self.index_info = tk.StringVar(value="0 / 0")
        self.xmin = tk.StringVar()
        self.xmax = tk.StringVar()
        self.ymin = tk.StringVar()
        self.ymax = tk.StringVar()

        self.wafer_df = pd.DataFrame()
        self.groups = []
        self.group_key_to_item = {}
        self.group_index = 0
        self.next_group_index = 0
        self.current_page_span = (0, 0)

        self._build_ui()

    def _build_ui(self):
        root = ttk.Frame(self, padding=8)
        root.pack(fill=tk.BOTH, expand=True)

        file_row = ttk.Frame(root)
        file_row.pack(fill=tk.X)

        ttk.Label(file_row, text="CSV").pack(side=tk.LEFT)
        ttk.Entry(file_row, textvariable=self.csv_path).pack(side=tk.LEFT, fill=tk.X, expand=True, padx=6)
        ttk.Button(file_row, text="Browse", command=self.browse_csv).pack(side=tk.LEFT)
        ttk.Button(file_row, text="Scan CSV", command=self.scan_csv_async).pack(side=tk.LEFT, padx=(4, 0))

        body = ttk.Frame(root)
        body.pack(fill=tk.BOTH, expand=True, pady=(8, 0))

        sidebar = ttk.Frame(body, width=230)
        sidebar.pack(side=tk.LEFT, fill=tk.Y, padx=(0, 10))
        sidebar.pack_propagate(False)

        plot_frame = ttk.Frame(body)
        plot_frame.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)

        selection_box = ttk.LabelFrame(sidebar, text="Selection", padding=6)
        selection_box.pack(fill=tk.BOTH, expand=True)

        self.lot_menu = MultiSelectList(selection_box, "lot_id", height=3, width=22)
        self.lot_menu.pack(fill=tk.BOTH, expand=True, pady=(0, 6))
        self.wafer_menu = MultiSelectList(selection_box, "wafer_id", height=4, width=22)
        self.wafer_menu.pack(fill=tk.BOTH, expand=True, pady=(0, 6))
        self.condition_menu = MultiSelectList(selection_box, "condition", command=self.on_filter_change, height=4, width=22)
        self.condition_menu.pack(fill=tk.BOTH, expand=True, pady=(0, 8))

        ttk.Button(selection_box, text="Load selection", command=self.load_selection_async).pack(fill=tk.X)

        nav_box = ttk.LabelFrame(sidebar, text="Page", padding=6)
        nav_box.pack(fill=tk.X, pady=(8, 0))

        nav_buttons = ttk.Frame(nav_box)
        nav_buttons.pack(fill=tk.X)
        ttk.Button(nav_buttons, text="Prev", command=lambda: self.move_page(-1)).pack(side=tk.LEFT, fill=tk.X, expand=True)
        ttk.Button(nav_buttons, text="Next", command=lambda: self.move_page(1)).pack(side=tk.LEFT, fill=tk.X, expand=True, padx=(6, 0))
        ttk.Label(nav_box, textvariable=self.index_info).pack(fill=tk.X, pady=(6, 0))

        range_box = ttk.LabelFrame(sidebar, text="Range", padding=6)
        range_box.pack(fill=tk.X, pady=(8, 0))

        x_row = ttk.Frame(range_box)
        x_row.pack(fill=tk.X)
        ttk.Label(x_row, text="X", width=2).pack(side=tk.LEFT)
        ttk.Entry(x_row, textvariable=self.xmin, width=8).pack(side=tk.LEFT, fill=tk.X, expand=True)
        ttk.Label(x_row, text="to").pack(side=tk.LEFT, padx=4)
        ttk.Entry(x_row, textvariable=self.xmax, width=8).pack(side=tk.LEFT, fill=tk.X, expand=True)

        y_row = ttk.Frame(range_box)
        y_row.pack(fill=tk.X, pady=(4, 0))
        ttk.Label(y_row, text="Y", width=2).pack(side=tk.LEFT)
        ttk.Entry(y_row, textvariable=self.ymin, width=8).pack(side=tk.LEFT, fill=tk.X, expand=True)
        ttk.Label(y_row, text="to").pack(side=tk.LEFT, padx=4)
        ttk.Entry(y_row, textvariable=self.ymax, width=8).pack(side=tk.LEFT, fill=tk.X, expand=True)

        range_buttons = ttk.Frame(range_box)
        range_buttons.pack(fill=tk.X, pady=(6, 0))
        ttk.Button(range_buttons, text="Apply", command=self.plot_current_page).pack(side=tk.LEFT, fill=tk.X, expand=True)
        ttk.Button(range_buttons, text="Reset", command=self.reset_range).pack(side=tk.LEFT, fill=tk.X, expand=True, padx=(6, 0))

        filter_box = ttk.LabelFrame(sidebar, text="Filters", padding=6)
        filter_box.pack(fill=tk.BOTH, expand=True, pady=(8, 0))

        self.pattern_menu = MultiSelectList(filter_box, "pattern_name", command=self.on_filter_change, height=6, width=22)
        self.pattern_menu.pack(fill=tk.BOTH, expand=True)
        ttk.Button(filter_box, text="Select all filters", command=self.select_all_filters).pack(fill=tk.X, pady=(8, 0))

        color_box = ttk.LabelFrame(sidebar, text="Color", padding=6)
        color_box.pack(fill=tk.X, pady=(8, 0))
        self.color_menu = MultiSelectList(color_box, "color by", command=self.plot_current_page, height=2, width=22)
        self.color_menu.pack(fill=tk.X)

        ttk.Label(plot_frame, textvariable=self.current_info).pack(fill=tk.X, pady=(0, 4))
        self.figure = Figure(figsize=(12, 7.5), dpi=100)
        self.canvas = FigureCanvasTkAgg(self.figure, master=plot_frame)
        self.toolbar = NavigationToolbar2Tk(self.canvas, plot_frame, pack_toolbar=False)
        self.toolbar.update()
        self.toolbar.pack(fill=tk.X)
        self.canvas.get_tk_widget().pack(fill=tk.BOTH, expand=True)

        ttk.Label(root, textvariable=self.status, anchor=tk.W).pack(fill=tk.X, pady=(6, 0))

    def browse_csv(self):
        path = filedialog.askopenfilename(
            title="Select failbit_labeled.csv",
            filetypes=[("CSV files", "*.csv"), ("All files", "*.*")],
            initialdir=os.path.dirname(self.csv_path.get()) or os.getcwd(),
        )
        if path:
            self.csv_path.set(path)
            self.lot_menu.set_options([])
            self.wafer_menu.set_options([])

    def scan_csv_async(self):
        path = self.csv_path.get().strip()
        if not path:
            messagebox.showerror("Missing CSV", "Please select failbit_labeled.csv.")
            return
        if not os.path.exists(path):
            messagebox.showerror("CSV not found", path)
            return

        self.status.set("Scanning lot_id / wafer_id from CSV...")
        thread = threading.Thread(target=self._scan_csv_worker, args=(path,), daemon=True)
        thread.start()

    def _scan_csv_worker(self, path):
        try:
            lots, wafers, conditions = self._scan_lot_wafer_condition(path)
            self.after(0, lambda: self._finish_scan(lots, wafers, conditions))
        except Exception as exc:
            self.after(0, lambda: self._show_error("Scan failed", str(exc)))

    def _scan_lot_wafer_condition(self, path):
        lots = set()
        wafers = set()
        conditions = set()
        for chunk in pd.read_csv(path, chunksize=500000, usecols=lambda c: c in SCAN_COLS):
            if "lot_id" in chunk.columns:
                lots.update(compact_value(v) for v in chunk["lot_id"].dropna().unique())
            if "wafer_id" in chunk.columns:
                wafers.update(compact_value(v) for v in chunk["wafer_id"].dropna().unique())
            if "condition" in chunk.columns:
                conditions.update(compact_value(v) for v in chunk["condition"].dropna().unique())

        return sorted(lots), sorted(wafers, key=self._sort_key), sorted(conditions)

    def _finish_scan(self, lots, wafers, conditions):
        self.lot_menu.set_options(lots)
        self.wafer_menu.set_options(wafers)
        self.condition_menu.set_options(conditions)
        self.status.set(
            "Scanned CSV: %d lot_id values, %d wafer_id values, %d condition values."
            % (len(lots), len(wafers), len(conditions))
        )

    def load_selection_async(self):
        path = self.csv_path.get().strip()
        lots = self.lot_menu.selected_values()
        wafers = self.wafer_menu.selected_values()

        if not path:
            messagebox.showerror("Missing CSV", "Please select failbit_labeled.csv.")
            return
        if not os.path.exists(path):
            messagebox.showerror("CSV not found", path)
            return
        if not lots or not wafers:
            messagebox.showerror("Missing selection", "Please scan CSV and select at least one lot_id and wafer_id.")
            return

        self.status.set("Loading selected lot/wafer rows from CSV...")
        thread = threading.Thread(target=self._load_selection_worker, args=(path, lots, wafers), daemon=True)
        thread.start()

    def _load_selection_worker(self, path, lots, wafers):
        try:
            df = self._read_selection(path, lots, wafers)
            groups = self._build_groups(df)
            self.after(0, lambda: self._finish_load(df, groups, lots, wafers))
        except Exception as exc:
            self.after(0, lambda: self._show_error("Load failed", str(exc)))

    def _read_selection(self, path, lots, wafers):
        lot_set = set(str(v) for v in lots)
        wafer_set = set(str(v) for v in wafers)
        chunks = []
        for chunk in pd.read_csv(path, chunksize=500000, usecols=lambda c: c in BASE_COLS):
            if "wafer_id" not in chunk.columns:
                raise ValueError("CSV does not contain wafer_id column.")
            if "lot_id" not in chunk.columns:
                raise ValueError("CSV does not contain lot_id column.")

            part = chunk[
                chunk["lot_id"].astype(str).isin(lot_set)
                & chunk["wafer_id"].astype(str).isin(wafer_set)
            ]
            if not part.empty:
                chunks.append(part.copy())

        if not chunks:
            return pd.DataFrame(columns=BASE_COLS)

        df = pd.concat(chunks, ignore_index=True)
        df["physical_x"] = pd.to_numeric(df["physical_x"], errors="coerce")
        df["physical_y"] = pd.to_numeric(df["physical_y"], errors="coerce")
        df = df.dropna(subset=["physical_x", "physical_y"])
        df["pattern_name"] = df["pattern_name"].fillna("UNCLASSIFIED")
        if "pattern_id" not in df.columns:
            df["pattern_id"] = ""
        df["pattern_id"] = df["pattern_id"].fillna("").astype(str)
        self._add_group_key(df)
        return df

    def _build_groups(self, df):
        if df.empty:
            return []

        available_cols = [col for col in GROUP_COLS if col in df.columns]
        size_df = df.groupby(available_cols, dropna=False).size().reset_index(name="fail_count")

        sort_cols = [col for col in ["diex", "diey", "macro", "condition"] if col in size_df.columns]
        if sort_cols:
            size_df = size_df.sort_values(sort_cols, kind="mergesort")

        groups = []
        for _, row in size_df.iterrows():
            key = {}
            for col in available_cols:
                key[col] = compact_value(row[col])
            groups.append((key, int(row["fail_count"]), self._key_tuple(key)))
        return groups

    def _finish_load(self, df, groups, lots, wafers):
        self.wafer_df = df
        self.groups = groups
        self.group_key_to_item = {item[2]: item for item in groups}
        self.group_index = 0
        self.next_group_index = 0
        self.current_page_span = (0, 0)
        self._load_filter_options(df)

        if df.empty or not groups:
            self.index_info.set("0 / 0")
            self.current_info.set("No macro loaded")
            self.status.set("No rows found for selected lot/wafer.")
            self.clear_plot("No rows found for selected lot/wafer")
            return

        self.status.set(
            "Loaded lot_id=%s wafer_id=%s: %d failbits, %d macro views."
            % (",".join(lots), ",".join(wafers), len(df), len(groups))
        )
        self.plot_current_page()

    def _load_filter_options(self, df):
        if df.empty:
            self.pattern_menu.set_options([])
            self.condition_menu.set_options([])
            self.color_menu.set_options([])
            return

        pattern_options = df["pattern_name"].fillna("UNCLASSIFIED").value_counts().index.tolist()
        condition_options = sorted([compact_value(v) for v in df["condition"].dropna().unique()])
        had_condition_options = bool(self.condition_menu.options)
        selected_conditions = self.condition_menu.selected_values()
        self.pattern_menu.set_options(pattern_options)
        if had_condition_options:
            selected_conditions = [v for v in selected_conditions if v in set(condition_options)]
            self.condition_menu.set_options(condition_options, selected=selected_conditions)
        else:
            self.condition_menu.set_options(condition_options)
        self.color_menu.set_options(["pattern_name", "pattern_id"], selected=["pattern_name"])

    def move_page(self, step):
        if not self.groups:
            return
        if step > 0:
            self.group_index = self.next_group_index if self.next_group_index < len(self.groups) else 0
        else:
            self.group_index = max(0, self.current_page_span[0] - PAGE_SIZE)
        self.plot_current_page()

    def on_filter_change(self):
        if not self.groups:
            return
        self.group_index = 0
        self.plot_current_page()

    def select_all_filters(self):
        self.pattern_menu.select_all()
        self.condition_menu.select_all()

    def reset_range(self):
        self.xmin.set("")
        self.xmax.set("")
        self.ymin.set("")
        self.ymax.set("")
        self.plot_current_page()

    def plot_current_page(self):
        if not self.groups:
            self.clear_plot("No macro loaded")
            return

        try:
            x_range = parse_range(self.xmin.get(), self.xmax.get())
            y_range = parse_range(self.ymin.get(), self.ymax.get())
        except ValueError as exc:
            messagebox.showerror("Invalid range", str(exc))
            return

        filtered_df = self._filter_wafer_rows(x_range=x_range, y_range=y_range)
        self.figure.clear()
        axes = self.figure.subplots(PAGE_ROWS, PAGE_COLS).ravel()
        page_groups = self._visible_page_groups(filtered_df)
        shown_total = 0

        if not page_groups:
            self.clear_plot("No macro contains the selected pattern_name / condition / range.")
            self._set_page_labels(0)
            return

        for ax, item in zip(axes, page_groups):
            key, fail_count, group_key = item
            df = self._filter_group_rows(key, source_df=filtered_df)
            shown_total += len(df)
            self._plot_macro_axis(ax, key, fail_count, df, x_range, y_range)

        for ax in axes[len(page_groups):]:
            ax.set_axis_off()

        self.figure.tight_layout()
        self.canvas.draw_idle()
        self._set_page_labels(shown_total)

    def _visible_page_groups(self, filtered_df):
        if filtered_df.empty or GROUP_KEY_COL not in filtered_df.columns:
            self.current_page_span = (0, 0)
            self.next_group_index = len(self.groups)
            return []

        visible_keys = set(filtered_df[GROUP_KEY_COL].unique())
        page_groups = []
        idx = self.group_index
        first_idx = None
        last_idx = None

        while idx < len(self.groups) and len(page_groups) < PAGE_SIZE:
            item = self.groups[idx]
            group_key = item[2]
            if group_key in visible_keys:
                if first_idx is None:
                    first_idx = idx
                last_idx = idx
                page_groups.append(item)
            idx += 1

        if not page_groups and self.group_index >= len(self.groups):
            self.group_index = 0
            return self._visible_page_groups(filtered_df)

        if page_groups:
            self.current_page_span = (first_idx, last_idx)
            self.next_group_index = idx
        else:
            self.current_page_span = (0, 0)
            self.next_group_index = len(self.groups)

        return page_groups

    def _plot_macro_axis(self, ax, key, fail_count, df, x_range, y_range):
        if df.empty:
            ax.text(0.5, 0.5, "No points", ha="center", va="center", transform=ax.transAxes)
            ax.set_title(self._short_title(key, fail_count, 0), fontsize=8)
            ax.set_axis_off()
            return

        df = df.copy()
        color_fields = self._selected_color_fields(df)
        df["_color_label"] = self._color_labels(df, color_fields)
        color_counts = df["_color_label"].value_counts()
        color_map = self._color_map(color_counts.index.tolist())
        marker_size = self._marker_size(len(df))

        for label_value, count in color_counts.items():
            part = df[df["_color_label"] == label_value]
            ax.scatter(
                part["physical_x"],
                part["physical_y"],
                s=marker_size,
                alpha=0.82,
                linewidths=0,
                color=color_map.get(str(label_value), "tab:blue"),
                label="%s (%d)" % (label_value, count),
                rasterized=True,
            )

        ax.set_title(self._short_title(key, fail_count, len(df)), fontsize=8)
        ax.set_xlabel("x", fontsize=8)
        ax.set_ylabel("y", fontsize=8)
        ax.tick_params(labelsize=7)
        ax.grid(True, linewidth=0.3, alpha=0.30)

        if x_range is not None:
            low, high = x_range
            if low is not None and high is not None:
                ax.set_xlim(low, high)
        if y_range is not None:
            low, high = y_range
            if low is not None and high is not None:
                ax.set_ylim(low, high)

        ax.legend(fontsize=6, loc="best", frameon=False, markerscale=1.8)

    def _filter_current_group(self, key):
        return self._filter_group_rows(key)

    def _filter_wafer_rows(self, x_range=None, y_range=None):
        df = self.wafer_df

        selected_patterns = self.pattern_menu.selected_values()
        selected_conditions = self.condition_menu.selected_values()
        if "pattern_name" in df.columns and not self.pattern_menu.is_all_selected():
            df = df[df["pattern_name"].astype(str).isin(selected_patterns)]
        if "condition" in df.columns and not self.condition_menu.is_all_selected():
            df = df[df["condition"].astype(str).isin(selected_conditions)]

        if x_range is not None:
            low, high = x_range
            if low is not None:
                df = df[df["physical_x"] >= low]
            if high is not None:
                df = df[df["physical_x"] <= high]

        if y_range is not None:
            low, high = y_range
            if low is not None:
                df = df[df["physical_y"] >= low]
            if high is not None:
                df = df[df["physical_y"] <= high]

        return df

    def _filter_group_rows(self, key, source_df=None, max_rows=None):
        df = source_df if source_df is not None else self._filter_wafer_rows()
        if GROUP_KEY_COL in df.columns:
            df = df[df[GROUP_KEY_COL] == self._key_tuple(key)]
        else:
            mask = pd.Series(True, index=df.index)
            for col, value in key.items():
                mask &= df[col].astype(str) == str(value)
            df = df[mask]

        if max_rows is not None and len(df) > max_rows:
            return df.head(max_rows)

        return df.copy()

    def _set_page_labels(self, shown_total):
        if not self.groups:
            self.index_info.set("0 / 0")
            self.current_info.set("No macro loaded")
            return

        start = self.current_page_span[0] + 1
        end = self.current_page_span[1] + 1
        self.index_info.set("%d-%d / %d" % (start, end, len(self.groups)))
        self.current_info.set(
            "page=%d-%d | shown=%d | pattern_name=%s | condition=%s"
            % (
                start,
                end,
                shown_total,
                self.pattern_menu.text_var.get().replace("pattern_name: ", ""),
                self.condition_menu.text_var.get().replace("condition: ", ""),
            )
        )

    def _selected_color_fields(self, df):
        fields = [field for field in self.color_menu.selected_values() if field in df.columns]
        if fields:
            return fields
        if "pattern_name" in df.columns:
            return ["pattern_name"]
        return []

    def _color_labels(self, df, fields):
        if not fields:
            return pd.Series(["all"] * len(df), index=df.index)
        if len(fields) == 1:
            col = fields[0]
            labels = df[col].fillna("").astype(str)
            return labels.mask(labels == "", "NA")

        label_parts = []
        for col in fields:
            values = df[col].fillna("").astype(str).mask(lambda s: s == "", "NA")
            label_parts.append(col + "=" + values)

        labels = label_parts[0]
        for part in label_parts[1:]:
            labels = labels + " | " + part
        return labels

    def _color_map(self, labels):
        cmap = matplotlib.colormaps["tab20"]
        return {str(label): cmap(idx % cmap.N) for idx, label in enumerate(labels)}

    def _sort_key(self, value):
        text = str(value)
        try:
            return (0, int(text))
        except ValueError:
            return (1, text)

    def _key_tuple(self, key):
        return GROUP_KEY_SEP.join(str(key.get(col, "")) for col in GROUP_COLS)

    def _add_group_key(self, df):
        for col in GROUP_COLS:
            if col not in df.columns:
                df[col] = ""
        key_series = df[GROUP_COLS[0]].map(compact_value).astype(str)
        for col in GROUP_COLS[1:]:
            key_series = key_series + GROUP_KEY_SEP + df[col].map(compact_value).astype(str)
        df[GROUP_KEY_COL] = key_series

    def _short_title(self, key, fail_count, shown_count):
        return (
            "lot=%s wafer=%s dev=%s die=(%s,%s) macro=%s condition=%s\n"
            "fail=%d shown=%d"
            % (
                compact_value(key.get("lot_id", "NA")),
                compact_value(key.get("wafer_id", "NA")),
                compact_value(key.get("device#", "NA")),
                compact_value(key.get("diex", "NA")),
                compact_value(key.get("diey", "NA")),
                compact_value(key.get("macro", "NA")),
                compact_value(key.get("condition", "NA")),
                fail_count,
                shown_count,
            )
        )

    def _unique_text(self, col):
        if self.wafer_df.empty or col not in self.wafer_df.columns or not self.groups:
            return "%s=NA" % col

        key, _, _ = self.groups[self.group_index]
        df = self._filter_current_group(key)
        values = [compact_value(v) for v in df[col].dropna().unique()]
        if not values:
            return "%s=NA" % col
        if len(values) <= 3:
            return "%s=%s" % (col, ",".join(values))
        return "%s=%s..." % (col, ",".join(values[:3]))

    def clear_plot(self, text):
        self.figure.clear()
        ax = self.figure.add_subplot(111)
        ax.text(0.5, 0.5, text, ha="center", va="center", transform=ax.transAxes)
        ax.set_axis_off()
        self.canvas.draw_idle()

    def _marker_size(self, point_count):
        if point_count <= 2000:
            return 10
        if point_count <= 20000:
            return 5
        if point_count <= 100000:
            return 2
        return 0.7

    def _show_error(self, title, message):
        self.status.set("%s: %s" % (title, message))
        messagebox.showerror(title, message)


def main():
    app = FBMViewer()
    app.mainloop()


if __name__ == "__main__":
    main()
